server:
  host: ${server_host:http://localhost}
  port: 8080

spring:
  application:
    name: slasify
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:file:./data/slasify;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

jwt:
  secret: mySuperSecretKey12345-your-32-byte-minimum-secret-key
  expiration: 86400000


